name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker compose build
      
    - name: Create-DB
      run: docker compose up -d

    - name: Install psql client
      run: sudo apt-get install -y postgresql-client

    - name: Wait for Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U root; do
        echo "Waiting for postgres..."
        sleep 2
        done
      
    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml      
